#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
cd /var/tmp/build/[% project %]-[% c('version') %]

./bootstrap --prefix=$distdir -- -DCMAKE_USE_OPENSSL=OFF
make -j[% c('num_procs') %]
make install

cd /var/tmp/dist
mv cmake-build cmake
[% c('tar', {
        tar_src => cmake,
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]

