#!/bin/bash
[% c("var/set_default_env") -%]

# setup build tools
[% pc('rust', 'var/setup', { rust_tarfile => c('input_files_by_name/rust') }) %]

[% pc(c('var/build-toolchain'), 'var/setup', { build_toolchain_tarfile => c('input_files_by_name/build-toolchain') }) %]

tar -C $distdir -xf [% c('input_files_by_name/cmake') %]
export PATH=$distdir/cmake/bin:$PATH

# extract dependencies
tar -C $distdir -xf [% c('input_files_by_name/tor') %]
[% IF c("var/windows") || c("var/macos") %]
tar -C $distdir -xf [% c('input_files_by_name/wxWidgets') %]
export PATH=$distdir/wxWidgets/bin:$PATH
[% END -%]

# extract source
tar -C $builddir -xf [% project %]-[% c('version') %].tar.gz
tar -C $builddir/[% project %]-[% c('version') %]/src -xf [% c('input_files_by_name/ricochet-refresh-cargo-vendor') %]

cd $builddir/[% project %]-[% c('version') %]/

# setup cargo vendoring
pushd src/libtego_rs
mkdir -p .cargo
cat <<EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor/libtego_rs"

[net]
offline=true
EOF
popd

pushd src/ricochet-refresh-qt
mkdir -p .cargo
cat <<EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor/ricochet-refresh-qt"

[net]
offline=true
EOF
popd

# generate src tar
pushd $builddir
[% c('tar', {
        tar_src => project _ '-' _ c('version'),
        tar_args => '-czf ' _ dest_dir _ '/src-' _ c('filename'),
    }) %]
popd

# clang needs to be reminded where its c++ includes are
[% IF c("var/macos") -%]
  cppincludes=$distdir/toolchain-macos-clang/clang/include/c++/v1
  export CPLUS_INCLUDE_PATH=$cppincludes:$CPLUS_INCLUDE_PATH
  export PKG_CONFIG_LIBDIR=$sysrootdir/lib/pkgconfig
[% END -%]

[% IF c("var/linux-cross") -%]
  export PKG_CONFIG_LIBDIR="/usr/lib/[% c("var/compiler_target") %]/pkgconfig:/usr/share/pkgconfig"
[% END -%]

CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=MinSizeRel
             -DBUILD_QT_FRONTEND=OFF
             -DBUILD_WX_WIDGETS_FRONTEND=ON"

CMAKE_FLAGS="-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE $CMAKE_FLAGS"

# Always enable logging in testbuilds
[% IF c("var/testbuild") %]
    CMAKE_FLAGS="-DENABLE_RICOCHET_REFRESH_LOGGING=ON $CMAKE_FLAGS"
[% END -%]

[% IF c("var/linux-cross") -%]
    CMAKE_FLAGS="-DCMAKE_EXE_LINKER_FLAGS=-Wl,-rpath-link=/usr/lib/[% c("var/compiler_target") %] $CMAKE_FLAGS"
[% END -%]
[% IF c("var/windows") -%]
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Windows $CMAKE_FLAGS"
    [% IF c("var/windows-i686") -%]
        CMAKE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=i386 $CMAKE_FLAGS"
    [% END -%]
    [% IF c("var/windows-x86_64") -%]
        CMAKE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=x86_64 $CMAKE_FLAGS"
    [% END -%]
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_AR=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ar $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_AR=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ar $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_RANLIB=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ranlib $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_RANLIB=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ranlib $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_ASM_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-windows-clang/[% c('var/compiler_target') -%]/lib/ $CMAKE_FLAGS"
[% END -%]
[% IF c("var/macos") -%]
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-macos-clang/clang/lib/ $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Darwin $CMAKE_FLAGS"
[% END -%]


# [% IF c("var/pluggable_transports") %]
#     CMAKE_FLAGS="-DENABLE_PLUGGABLE_TRANSPORTS=ON $CMAKE_FLAGS"
#     CMAKE_FLAGS="-DTOR_EXPERT_BUNDLE=$rootdir/[% c('input_files_by_name/tor-expert-bundle') %] $CMAKE_FLAGS"
# [% END -%]

CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=$distdir/ricochet-refresh-dist $CMAKE_FLAGS"

mkdir build && cd build
export SOURCE_DATE_EPOCH='[% c("timestamp") %]'
RICOCHET_REFRESH_VERSION=[% c('version') %] cmake -S ../src --trace-expand $CMAKE_FLAGS '-DCARGO_FLAGS=[% pc('rust', 'var/cargo-flags') %]'

cmake --build . -j[% c('num_procs') %] --verbose
cmake --install .

bindir=$projdir

mv $distdir/ricochet-refresh-dist/bin/* $projdir

# [% IF c("var/pluggable_transports") -%]
# # remove extraneous non-executable files
# find $bindir/pluggable_transports -type f ! -executable -exec rm {} \;
# [% END -%]

# tor
cp $distdir/tor/bin/tor[% IF c("var/windows") %].exe[% END %] $bindir/.

# license files
cp $builddir/[% project %]-[% c('version') %]/LICENSE $distdir/ricochet-refresh/.

cd $distdir
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
