#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/build -xf $rootdir/[% c("input_files_by_name/gcc-source") %]
cd /var/tmp/build/[% project %]-[% c("version") %]

./configure --prefix=$distdir [% c("var/configure_opt") %]
make -j[% c("num_procs") %]
make install
ln -s gcc $distdir/bin/cc

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
