#!/bin/bash
[% c("var/set_default_env") -%]
[% pc(c('var/build-toolchain'), 'var/setup', { build_toolchain_tarfile => c('input_files_by_name/build-toolchain') }) %]

# extract dependencies
tar -C $distdir -xf [% c('input_files_by_name/cmake') %]
export PATH="$distdir/cmake/bin:$PATH"
# extract wxrc
tar -C $distdir -xf $rootdir/[% c("input_files_by_name/wxrc") %]

# extract wxWidgets source
tar -C $builddir -xf $rootdir/[% c("input_files_by_name/wxWidgets-source") %]
cd $builddir/wxWidgets-source



CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=MinSizeRel
             -DCMAKE_INSTALL_PREFIX='$projdir'
             -DwxBUILD_SHARED=OFF
             -DwxUSE_AUI=OFF
             -DwxUSE_STC=OFF
             -DwxUSE_SOCKETS=OFF
             -DwxUSE_PROTOCOL=OFF
             -DwxUSE_PROTOCOL_FTP=OFF
             -DwxUSE_PROTOCOL_HTTP=OFF
             -DwxUSE_URL=OFF
             -DwxUSE_FS_INET=OFF
             -DwxUSE_WEBVIEW=OFF
             -DwxBUILD_COMPATIBILITY=3.2"

[% IF c("var/windows") -%]
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-windows-clang/[% c('var/compiler_target') -%]/lib/ $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Windows $CMAKE_FLAGS"
    CMAKE_FLAGS="-DwxBUILD_TOOLKIT=msw $CMAKE_FLAGS"
[% ELSIF c("var/macos") -%]
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-macos-clang/clang/lib/ $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Darwin $CMAKE_FLAGS"
    CMAKE_FLAGS="-DwxBUILD_TOOLKIT=osx_cocoa $CMAKE_FLAGS"
    CMAKE_FLAGS="-DwxBUILD_PRECOMP=OFF $CMAKE_FLAGS"
[% END %]

cmake -S . ${CMAKE_FLAGS}
cmake --build . -j[% c('num_procs') %]
cmake --build . --target install

# mingw expects libraries to have 'lib' prefix
pushd "$projdir/lib"
    ln -s wxsharpyuv.a libwxsharpyuv.a
    ln -s wxwebp.a libwxwebp.a
    ln -s wxwebpdemux.a libwxwebpdemux.a
popd

# swap out wxrc with linux-x86_64 build
rm $projdir/bin/wxrc*
cp $distdir/wxrc/bin/wxrc-3.3 $projdir/bin/.
ln -s /var/tmp/rbm/dist/wxWidgets/bin/wxrc-3.3 $projdir/bin/wxrc

cd $distdir
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
