#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
cd /var/tmp/build/[% project %]-[% c('version') %]

./autogen.sh
./configure --prefix $distdir --disable-shared --without-zlib

make -j[% c('num_procs') %]
make install

rm -rf $distdir/lib $distdir/include

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
