#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/dist -xf [% c('input_files_by_name/rust') %]
export PATH=/var/tmp/dist/rust/bin:$PATH
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
cd /var/tmp/build/[% project %]-[% c('version') %]/apple-codesign

mkdir -p /var/tmp/dist/rcodesign
cargo install --bin rcodesign --path . --root /var/tmp/dist/rcodesign

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
