#!/bin/bash
[% c('var/set_default_env') -%]
builddir=/var/tmp/build/builddir

prefix=$distdir
arch=[% c('var/arch') %]
host=$arch-w64-mingw32

PATH="$prefix/bin:$PATH"

# extract binutils source
tar -xf [% c('input_files_by_name/binutils-source') %]
mv binutils-[% c('var/binutils_version') %] binutils

# buid binutils
mkdir -p $builddir/binutils
pushd $builddir/binutils
  $rootdir/binutils/configure \
    --prefix=$prefix --disable-shared --enable-static --with-sysroot=$prefix --target=$host \
    --disable-multilib --enable-lto --disable-gdb --enable-deterministic-archives
  make -j [% c('num_procs') %]
  make install
popd

# extract mingw sources
tar -xf [% project %]-[% c('version') %].tar.gz
mv [% project %]-[% c('version') %] [% project %]

# build headers
mkdir -p $builddir/mingw-w64-headers
pushd $builddir/mingw-w64-headers
  $rootdir/[% project %]/mingw-w64-headers/configure --host=$host --prefix=$distdir/$host \
    --with-default-msvcrt=msvcrt --enable-sdk=all --enable-idl
  make install
popd

# extract gcc source
tar -xf [% c('input_files_by_name/gcc-source') %]
mv gcc-[% c('var/gcc_version') %] gcc

# build gcc
mkdir -p $builddir/gcc
pushd $builddir/gcc
    $rootdir/gcc/configure --prefix=$distdir --target=$host --disable-shared --enable-static \
      --disable-multilib --enable-languages=c,c++ --disable-nls --enable-threads=posix [% c('var/x86_dwarf2') %]
    make -j [% c('num_procs') %] all-gcc
    make install-gcc
popd

# build crt
mkdir -p $builddir/mingw-w64-crt
pushd $builddir/mingw-w64-crt
  $rootdir/[% project %]/mingw-w64-crt/configure --prefix=$distdir/$host --host=$host \
    --with-default-msvcrt=msvcrt --with-sysroot=$distdir/$host [% c('var/crt_lib') %]
  make -j [% c('num_procs') %]
  make install
popd

# build winpthreads
mkdir -p $builddir/mingw-w64-winpthreads
pushd $builddir/mingw-w64-winpthreads
  $rootdir/[% project %]/mingw-w64-libraries/winpthreads/configure --prefix=$distdir/$host \
    --host=$host --disable-shared --enable-static
  make -j [% c('num_procs') %]
  make install
popd

#build widl
mkdir -p $builddir/mingw-w64/widl
pushd $builddir/mingw-w64/widl
  $rootdir/[% project %]/mingw-w64-tools/widl/configure --prefix=$distdir --target=$host
  make -j [% c('num_procs') %]
  make install
popd

# build gcc
pushd $builddir/gcc
  make -j [% c('num_procs') %]
  make install
popd

# package
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
