#!/bin/bash

if [ "$1" == "--sdk" ] && [ "$2" == "macosx" ]; then
    if [ "$3" == "-show-sdk-version" ] || [ "$3" == "--show-sdk-version" ]; then
        echo "11.0"
    fi
    if [ "$3" == "--show-sdk-path" ]; then
        echo "$distdir/toolchain-macos-clang/Developer/SDKs/MacOSX11.0.sdk"
    fi
fi

