#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/dist -xf [% c('input_files_by_name/ricochet-refresh') %]

[% IF c("var/windows") %]
    pushd /var/tmp/dist
        echo [% c("version") %] > ricochet-refresh/VERSION
        mv ricochet-refresh "Ricochet Refresh"
        zip -r ricochet.zip "Ricochet Refresh"
        mv ricochet.zip $distdir/ricochet-refresh-[% c("version") %]-windows-[% c("var/arch") %].zip
    popd
[% END %]

# make our output directory and copy outputs
mkdir -p [% dest_dir _ '/' _ c('filename') %]
cp -a $distdir/* [% dest_dir _ '/' _ c('filename') %]/.
