#!/bin/bash
[% c("var/set_default_env") -%]

# windows packaging
[% IF c("var/windows") %]
    tar -C /var/tmp/dist -xf [% c('input_files_by_name/ricochet-refresh') %]
    pushd /var/tmp/dist
        echo [% c("version") %] > ricochet-refresh/VERSION
        mv ricochet-refresh "Ricochet Refresh"
        zip -r $distdir/ricochet-refresh-[% c("version") %]-windows-[% c("var/arch") %].zip "Ricochet Refresh"
    popd
[% END %]

# linux packaging
[% IF c("var/linux") %]
    mv [% c('input_files_by_name/ricochet-refresh') %] $distdir/ricochet-refresh-[% c("version") %]-linux-[% c("var/arch") %].tar.gz
[% END %]

# macos packaging
[% IF c("var/macos") %]
    tar -C /var/tmp/dist -xf [% c('input_files_by_name/ricochet-refresh') %]
    tar -C /var/tmp/dist -xf [% c('input_files_by_name/libdmg') %]
    export PATH="/var/tmp/dist/libdmg-hfsplus:$PATH"

[% END %]


# make our output directory and copy outputs
mkdir -p [% dest_dir _ '/' _ c('filename') %]
cp -a $distdir/* [% dest_dir _ '/' _ c('filename') %]/.
