#!/bin/bash
[% c("var/set_default_env") -%]

# copy all our packages to publish dir

cp [% c('input_files_by_name/linux-i686') %]/* [% dest_dir %]/.
cp [% c('input_files_by_name/linux-x86_64') %]/* [% dest_dir %]/.
cp [% c('input_files_by_name/macos-x86_64') %]/* [% dest_dir %]/.
cp [% c('input_files_by_name/macos-aarch64') %]/* [% dest_dir %]/.
cp [% c('input_files_by_name/windows-i686') %]/* [% dest_dir %]/.
cp [% c('input_files_by_name/windows-x86_64') %]/* [% dest_dir %]/.

# calculat hshes of artifacts

pushd [% dest_dir %]
echo -n > sha256sums.txt
for file in $(ls | sort)
do
    sha256sum $file >> sha256sums.txt
done
popd