#!/bin/bash
[% c("var/set_default_env") -%]

tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.xz
./configure --prefix=$distdir [% c('var/configure_opt') %]
make -j[% c("num_procs") %]
make install

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
