#!/bin/bash
[% c("var/set_default_env") -%]

tar -xvf [% c('input_files_by_name/wxrc-build') %]
mv wxrc-build/* $projdir/.

cd $distdir
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
